### PR TITLE
Don't execute reducer multiple times

### LINKED ISSUE #4: Reducer executed multiple times
Hi,

I noticed when I started using the logger my reducer was getting called more than once for each dispatched action.  Looking at the logger function code I see it's calling the reducer twice.

Also, seems that if you use the logger function inside the React component function the reducer ends up being called even more times.

btw, cool library! Thanks!

### PR DESCRIPTION
**Pull request by victorporof**
Fixes #4 

Signed-off-by: Victor Porof <victor.porof@gmail.com>

### CODE REVIEW

**Comment by victorporof** [comment]
Review ping.

**Review by tamircher — APPROVED** [review]
thanks, works great

**Comment by DannyDelott** [comment]
@jefflombard ping on this 🙂

**Comment by jefflombard** [comment]
@DannyDelott Thanks for the ping

**Comment by jefflombard** [comment]
@victorporof Thanks for the PR! Sorry for not seeing this until now

**Pull request merged**
